---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: openapi

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Generate token
        id: token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
        with:
          app_id: ${{ secrets.TOKEN_EXCHANGE_APP }}
          installation_retrieval_mode: id
          installation_retrieval_payload: ${{ secrets.TOKEN_EXCHANGE_INSTALL }}
          private_key: ${{ secrets.TOKEN_EXCHANGE_KEY }}
          permissions: >-
            {"contents": "write", "pull_requests": "write"}

      - name: Checkout source
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run install
        run: bundle install

      - name: Run generate
        run: bash hack/generate-client.sh

      - name: Create request
        id: pr
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          commit-message: "feat: automated openapi client update"
          delete-branch: true
          branch: openapi-client-update
          title: "feat: automated openapi client update"
          body: "New openapi client generated, automerge should handle that!"
          labels: openapi
          committer: GitHub Actions <github@webhippie.de>
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve request
        if: ${{ steps.pr.outputs.pull-request-url }}
        run: gh pr review --approve "${{ steps.pr.outputs.pull-request-url }}"
        env:
          GH_TOKEN: ${{ steps.token.outputs.token }}

      - name: Enable automerge
        if: ${{ steps.pr.outputs.pull-request-url }}
        run: gh pr merge --rebase --auto "${{ steps.pr.outputs.pull-request-url }}"
        env:
          GH_TOKEN: ${{ steps.token.outputs.token }}

...
