---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: openapi

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Generate token
        id: token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2
        with:
          app-id: ${{ secrets.TOKEN_EXCHANGE_APP }}
          private-key: ${{ secrets.TOKEN_EXCHANGE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - name: Checkout source
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run install
        run: bundle install

      - name: Run generate
        run: bash hack/generate-client.sh

      - name: Create request
        id: pr
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8
        with:
          commit-message: "feat: automated openapi client update"
          delete-branch: true
          branch: openapi-client-update
          title: "feat: automated openapi client update"
          body: "New openapi client generated, automerge should handle that!"
          labels: openapi
          committer: GitHub Actions <github@webhippie.de>
          token: ${{ steps.token.outputs.token }}

      - name: Approve request
        if: ${{ steps.pr.outputs.pull-request-url }}
        run: gh pr review --approve "${{ steps.pr.outputs.pull-request-url }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable automerge
        if: ${{ steps.pr.outputs.pull-request-url }}
        run: gh pr merge --rebase --auto "${{ steps.pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ steps.token.outputs.token }}

...
